"""add question status

Revision ID: 636d1c93c699
Revises: 7d82a54a4e37
Create Date: 2026-02-15 08:50:27.708882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '636d1c93c699'
down_revision: Union[str, Sequence[str], None] = '7d82a54a4e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('ai_generation_status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'ai_generation_status')
    # ### end Alembic commands ###
