"""add question_text to questions

Revision ID: 6a8194a5eb0c
Revises: 636d1c93c699
Create Date: 2026-02-19 15:19:05.182779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8194a5eb0c'
down_revision: Union[str, Sequence[str], None] = '636d1c93c699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('question_text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'question_text')
    # ### end Alembic commands ###
