"""add academic profile

Revision ID: db1e5801c4c2
Revises: ceff9fed123e
Create Date: 2026-02-14 13:26:56.933626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1e5801c4c2'
down_revision: Union[str, Sequence[str], None] = 'ceff9fed123e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('enrollment_number', sa.String(length=100), nullable=False),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('batch', sa.String(length=20), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('class_section', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], name=op.f('fk_student_profiles_attempt_id_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_profiles')),
    sa.UniqueConstraint('attempt_id', name=op.f('uq_student_profiles_attempt_id'))
    )
    op.drop_column('attempts', 'student_name')
    op.drop_column('attempts', 'enrollment_number')
    op.add_column('quizzes', sa.Column('academic_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'academic_type')
    op.add_column('attempts', sa.Column('enrollment_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('attempts', sa.Column('student_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
