"""add settings column to quizzes

Revision ID: f09b23cd72cb
Revises: 3c4d5e6f7a8b
Create Date: 2026-03-20 01:29:10.481106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f09b23cd72cb'
down_revision: Union[str, Sequence[str], None] = '3c4d5e6f7a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_attempts_enrollment_number'), 'attempts', ['enrollment_number'], unique=False)
    op.alter_column('auth_otps', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'duration',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'default_marks',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'shuffle_questions',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'shuffle_options',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'require_fullscreen',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'block_tab_switch',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'block_copy_paste',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'violation_limit',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'negative_marking',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'penalty_wrong',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'violation_penalty',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'attempts_allowed',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'allow_resume',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('quiz_settings', 'prevent_duplicate',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_quiz_settings_owner_user_id'), table_name='quiz_settings')
    op.drop_index(op.f('ix_quiz_settings_quiz_id'), table_name='quiz_settings')
    op.add_column('quizzes', sa.Column('settings', sa.JSON(), server_default=sa.text("'{}'"), nullable=False))
    op.drop_constraint(op.f('uq_quizzes_public_slug'), 'quizzes', type_='unique')
    op.drop_column('quizzes', 'public_slug')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('public_slug', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('uq_quizzes_public_slug'), 'quizzes', ['public_slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('quizzes', 'settings')
    op.create_index(op.f('ix_quiz_settings_quiz_id'), 'quiz_settings', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_settings_owner_user_id'), 'quiz_settings', ['owner_user_id'], unique=False)
    op.alter_column('quiz_settings', 'prevent_duplicate',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'allow_resume',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'attempts_allowed',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'violation_penalty',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'penalty_wrong',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'negative_marking',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'violation_limit',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'block_copy_paste',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'block_tab_switch',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'require_fullscreen',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'shuffle_options',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'shuffle_questions',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'default_marks',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('quiz_settings', 'duration',
               existing_type=sa.INTEGER(),
               server_default=sa.text('60'),
               existing_nullable=False)
    op.alter_column('auth_otps', 'attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_attempts_enrollment_number'), table_name='attempts')
    # ### end Alembic commands ###
